# Site settings
title:          ROOFTOP HERO
description:    ""
url:            "https://rakjido.github.io"

# Google Analytics
google_analytics: UA-148960515-1

# Author
author:
  name:         ROOFTOP HERO
  url:          https://rakjido.github.io
  email:        admin@naver.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year/:month/:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale